// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXgtqK44DsqAQo7nB6puFKh4lpI5sMNio',
    appId: '1:458583265582:web:a43906a600e2b15f53eabf',
    messagingSenderId: '458583265582',
    projectId: 'talkbuddyai',
    authDomain: 'talkbuddyai.firebaseapp.com',
    storageBucket: 'talkbuddyai.appspot.com',
    measurementId: 'G-8MLK8KC8CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkJFwU26-Dk21SP6kCOKXRo1wMAEXuBU',
    appId: '1:458583265582:android:618f2a9068dd599c53eabf',
    messagingSenderId: '458583265582',
    projectId: 'talkbuddyai',
    storageBucket: 'talkbuddyai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEAbcGtnchaJGdyIFMrSbKgW7vR5GrGtQ',
    appId: '1:458583265582:ios:908b7defa765845a53eabf',
    messagingSenderId: '458583265582',
    projectId: 'talkbuddyai',
    storageBucket: 'talkbuddyai.appspot.com',
    iosBundleId: 'com.example.talkbuddyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEAbcGtnchaJGdyIFMrSbKgW7vR5GrGtQ',
    appId: '1:458583265582:ios:fcdcb23b747a6b8e53eabf',
    messagingSenderId: '458583265582',
    projectId: 'talkbuddyai',
    storageBucket: 'talkbuddyai.appspot.com',
    iosBundleId: 'com.example.talkbuddyai.RunnerTests',
  );
}
